# Generated by Django 3.1.3 on 2020-11-30 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20201130_1748'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Create',
        ),
    ]
