# Generated by Django 3.1.3 on 2020-11-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=3)),
                ('gender', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('reason_for_referral', models.CharField(max_length=250)),
            ],
        ),
    ]
