# Generated by Django 3.1.3 on 2020-11-29 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20201129_1933'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Join',
            new_name='Patient',
        ),
    ]
