# Generated by Django 3.1.3 on 2020-11-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='age',
            field=models.CharField(max_length=30),
        ),
    ]
