# Generated by Django 3.1.3 on 2020-11-30 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20201130_1818'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Create',
            new_name='SignUp',
        ),
    ]
