# Generated by Django 3.0.8 on 2021-01-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_documentationpa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('reason_why', models.CharField(max_length=250)),
                ('meeting', models.CharField(max_length=250)),
                ('diagnosis', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='DocumentationPA',
        ),
    ]
