# Generated by Django 3.1.3 on 2021-01-10 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20210110_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='subject',
            field=models.CharField(max_length=20),
        ),
    ]
