# Generated by Django 3.1.3 on 2021-01-10 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20210110_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='diagnosis',
            field=models.CharField(blank=True, default='a', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='meeting',
            field=models.CharField(blank=True, default='a', max_length=40),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reason_why',
            field=models.CharField(blank=True, default='a', max_length=40),
        ),
    ]
