# Generated by Django 3.1.3 on 2021-01-10 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20210110_0447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='diagnosis',
        ),
    ]
