# Generated by Django 3.1.3 on 2021-01-10 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_remove_profile_diagnosis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='SOME STRING', max_length=20)),
                ('full_name', models.CharField(max_length=20)),
                ('passport_num', models.CharField(max_length=20)),
                ('request', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
